# Generated by Django 5.2.7 on 2025-11-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Conta Bloqueada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cadastrado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cadastrado Por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='E-mail Verificado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ip_cadastro',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Cadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tentativas_login_falhas',
            field=models.IntegerField(default=0, verbose_name='Tentativas de Login Falhas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_tentativa_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa de Login'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('cadastro_cliente', 'Cadastro de Cliente'), ('cadastro_imovel', 'Cadastro de Imóvel'), ('login', 'Login'), ('logout', 'Logout'), ('alteracao_dados', 'Alteração de Dados'), ('exclusao', 'Exclusão')], max_length=50, verbose_name='Tipo de Ação')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário')),
                ('cpf_usuario', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do Usuário')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_audito_timesta_8a238d_idx'), models.Index(fields=['tipo_acao', '-timestamp'], name='core_audito_tipo_ac_456f70_idx'), models.Index(fields=['cpf_usuario', '-timestamp'], name='core_audito_cpf_usu_f1a398_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Login Bem-sucedido')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('motivo_falha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da Falha')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cpf', '-timestamp'], name='core_logina_cpf_752dcb_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_logina_ip_addr_55d563_idx')],
            },
        ),
    ]
